version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    command: npm run start:prod
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
