import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.coerce.number().default(3157),
  DATABASE_URL: z.string(),
  USE_REDIS: z.string().default('false'),
  REDIS_HOST: z.string().default('redis'),
  REDIS_PORT: z.coerce.number().default(6379),
  REDIS_PASSWORD: z.string().default(''),
  JWT_SECRET: z.string(),
  JWT_EXPIRATION_TIME: z.coerce.number().default(3600),
  CORS_ORIGIN: z.string().default('*'),
  RESERVATIONS_PORT: z.string().default('3158'),
  RESERVATIONS_HOST: z.string().default('reservations'),
  RESERVATIONS_TCP_PORT: z.coerce.number().default(3003),
  AUTH_TCP_HOST: z.string().default('auth'),
  AUTH_TCP_PORT: z.coerce.number().default(3001),
  PAYMENTS_HOST: z.string().default('payments'),
  PAYMENTS_PORT: z.coerce.number().default(3159),
  PAYMENTS_TCP_PORT: z.coerce.number().default(3002),
  NOTIFICATIONS_HOST: z.string().default('notifications'),
  NOTIFICATIONS_PORT: z.coerce.number().default(3160),
  NOTIFICATIONS_TCP_PORT: z.coerce.number().default(3003),
  STRIPE_SECRET_KEY: z.string(),
  STRIPE_SUCCESS_URL: z.string(),
  STRIPE_CANCEL_URL: z.string(),
  STRIPE_WEBHOOK_SECRET: z.string(),
  INTER_SERVICE_SECRET: z.string(),
  SMTP_USER: z.string(),
  GOOGLE_OAUTH_CLIENT_ID: z.string(),
  GOOGLE_OAUTH_CLIENT_SECRET: z.string(),
  GOOGLE_OAUTH_REFRESH_TOKEN: z.string(),
});
